# Generated by Django 5.0.4 on 2024-04-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showsession',
            name='show_time',
            field=models.DateTimeField(),
        ),
    ]
