# Generated by Django 5.0.4 on 2024-04-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0003_alter_showsession_show_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showsession',
            options={'ordering': ['-show_time']},
        ),
    ]
