# Generated by Django 5.0.4 on 2024-04-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0004_alter_showsession_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronomyshow',
            name='theme',
            field=models.ManyToManyField(related_name='astronomy_shows', to='planetarium.showtheme'),
        ),
    ]
