# Generated by Django 5.0.4 on 2024-04-05 13:22

import planetarium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0007_alter_astronomyshow_themes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronomyshow',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=planetarium.models.show_image_path),
        ),
    ]
